language: scala
scala:
  - 2.11.12
  - 2.12.11
  - 2.13.3
jdk:
  - openjdk8
dist: xenial
sudo: false
script:
- sbt ++$TRAVIS_SCALA_VERSION test unidoc
- git diff --exit-code
matrix:
  include:
  - jdk: openjdk11
    scala: 2.12.11
    script:
    - sbt ++$TRAVIS_SCALA_VERSION test
